name: Auto Close Issue if Checkbox Not Ticked

on:
  issues:
    types: 
      - opened

jobs:
  check-checkbox:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the checkbox is ticked
        id: check_checkbox
        run: |
          # Extract the issue body
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          # Check if the checkbox is ticked
          if echo "$ISSUE_BODY" | grep -q '\- \[x\] I understand'; then
            echo "Checkbox is ticked"
            echo "checkbox_ticked=true" >> $GITHUB_ENV
          else
            echo "Checkbox is not ticked"
            echo "checkbox_not_ticked=true" >> $GITHUB_ENV
          fi

      - name: Close issue if checkbox not ticked
        if: env.checkbox_not_ticked == 'true'
        run: |
          # Post a comment to the issue
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body": "You did not agree to the terms and conditions. Therefore, this issue will be closed."}'

          # Close the issue
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"state": "closed"}'

      - name: Thank user if checkbox is ticked
        if: env.checkbox_ticked == 'true'
        run: |
          # Post a thank-you comment to the issue
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body": "Thank you for requesting a subdomain! Please be patient as we process your request. If not included in the description, kindly link the repository associated with this request."}'
